# Class 4 Pratice

In [13]:
def my_func():
  print("This is my function")
my_func()

This is my function


In [14]:
def func_num():
  return 4

temp_var = func_num
print(f"the result from fucntion is {temp_var()}")

the result from fucntion is 4


In [15]:
def factorial_func(num):
  if num==1:
    return 1
  return num * factorial_func(num - 1)

In [16]:
def outer_func(num):
  def inner_func(num):
    return num * num
  return inner_func

t_var = outer_func(5)
print("the answer is: ", t_var(5))

the answer is:  25


In [17]:
def hello(name):
  """ this function says hello to any person """
  print("hello: ", name)

hello("Zain Ali")
print(help(hello))

hello:  Zain Ali
Help on function hello in module __main__:

hello(name)
    this function says hello to any person

None


In [18]:
global_var = 10
def test_func():
  global global_var
  global_var = 5
  print("the global var inside function is: ", global_var)
test_func()
print("the global var is: ", global_var)

the global var inside function is:  5
the global var is:  5


In [19]:
import numpy as np

nu_array = np.array([1, 2, 3, 4, 5, 6])

print("numpy array is: ", nu_array)

nu_array = np.zeros((3, 3))

print("the changed array is: ",nu_array)

nu_array = np.ones((5, 4))

print("the ones array is: ",nu_array)

nu_array = np.full((5,3), 8)

print("the full array is: ",nu_array)

nu_array = np.eye(5)

print("the unit matrix is: ",nu_array)

nu_array = np.arange(1,10,2)

print("the arranged array is: ", nu_array)

numpy array is:  [1 2 3 4 5 6]
the changed array is:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
the ones array is:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
the full array is:  [[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]
the unit matrix is:  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
the arranged array is:  [1 3 5 7 9]


In [20]:
random_arr = np.random.rand(3,3)

print(random_arr)

[[0.91518688 0.38484285 0.65912927]
 [0.25856472 0.02750691 0.03164857]
 [0.75226093 0.21903277 0.58098728]]


In [21]:
random_arr = np.random.randint(1,15,(3,3))
print(random_arr)

[[ 2  4 10]
 [13  3 12]
 [ 7  7  2]]


In [22]:
random_arr = np.random.randint(1,15,(3,3))
print("random arrays: ",random_arr)
print("its shape is :", random_arr.shape)

random arrays:  [[ 4 13  2]
 [ 3 11 12]
 [ 5  3 12]]
its shape is : (3, 3)


In [23]:
t_var = np.array([1, 2, 3, 4, 5, 6])
t_var = t_var.reshape(2,3)
print("rearranged t_var is: ",t_var)

rearranged t_var is:  [[1 2 3]
 [4 5 6]]


In [24]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 2, 2, 2, 2])

print("the sum of both arrays is: ", arr1 + arr2)
print("the sqrt of array 2 is: ", np.sqrt(arr2))
print("the minimum of array1 is: ", np.min(arr1))

the sum of both arrays is:  [3 4 5 6 7]
the sqrt of array 2 is:  [1.41421356 1.41421356 1.41421356 1.41421356 1.41421356]
the minimum of array1 is:  1
